# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Whit Kemmey
tagline:             Whit's Blog
url:                 http://blog.whitkemmey.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Whit Kemmey
  url:               https://twitter.com/wkemmey
  email:             whit.kemmey@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/wkemmey/blog

# links for the header
main_site:           http://www.whitkemmey.com
pages_list:
  Blog:              http://blog.whitkemmey.com
  Archive:           /archive
  Feed:              /atom.xml
  About:             /about

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      comments: true
